### ISSUE TITLE
Sem 8 STQA resources missing

### ISSUE THREAD

**Issue by djscedmw2022** [junaidgirkar/DJSCE#1]
Junaid Bhai please STQA ke resources kahi se mile toh upload kar do...
![5iprog](https://github.com/junaidgirkar/DJSCE/assets/159225138/a4887ad6-737d-48e4-bfc2-7b7a2fb47904)

**Comment by junaidgirkar** [comment]
Sorry bro. Just not possible as no one had taken that elective from my batch.

![image](https://github.com/junaidgirkar/DJSCE/assets/60307291/82c8c9ed-052e-4ff2-bd06-2f5cf8a3120b)

**Comment by junaidgirkar** [comment]
Also @djscedmw2022 whos this? I'm curious 😂. Drop me a msg or email (if you don't have my number)
